---
title: "Quiz"
format:
  live-html: 
    theme: 
      - zephyr
      - ../../html/custom.scss
    knitr:
      opts_chunk:
        dev: "ragg_png"
        dpi: 300 
    toc: false
    section-divs: true
    include-after-body: 
      - text: |
          <script src="/js/progressive-reveal.js"></script>

engine: knitr

webr:
  packages:
    - ggplot2
---

{{< include ../../_extensions/r-wasm/live/_knitr.qmd >}}

```{r include=FALSE}
knitr::opts_chunk$set(
  fig.width = 6,
  fig.height = 6 * 0.618,
  fig.retina = 3,
  dev = "ragg_png",
  fig.align = "center",
  out.width = "70%"
)

library(tidyverse)

source(here::here("R", "helpers.R"))
```

In this tutorial, you learned how to customize the graphs that you make with ggplot2 in several ways. You learned how to:

* Zoom in on regions of the graph
* Add titles, subtitles, and annotations
* Add themes
* Add color scales
* Adjust legends

To cement your skills, combine what you've learned to recreate the plot below.

```{r echo=FALSE, message=FALSE}
ggplot(diamonds, aes(x = carat, y = price)) +
  geom_point() + 
  geom_smooth(aes(color = cut), se = FALSE) +  
  labs(title = "Ideal cut diamonds command the best price for every carat size",
       subtitle = "Lines show GAM estimate of mean values for each level of cut",
       caption = "Data provided by Hadley Wickham",
       x = "Log Carat Size",
       y = "Log Price Size",
       color = "Cut Rating") +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_brewer(palette = "Greens") +
  theme_light()
```

::: {.panel-tabset}
## {{< fa code >}}&ensp;Interactive editor

```{webr}



```

## {{< fa circle-check >}}&ensp;Solution

```r
ggplot(data = diamonds, mapping = aes(x = carat, y = price)) +
  geom_point() + 
  geom_smooth(mapping = aes(color = cut), se = FALSE) +  
  labs(title = "Ideal cut diamonds command the best price for every carat size",
       subtitle = "Lines show GAM estimate of mean values for each level of cut",
       caption = "Data provided by Hadley Wickham",
       x = "Log Carat Size",
       y = "Log Price Size",
       color = "Cut Rating") +
  scale_x_log10() +
  scale_y_log10() +
  scale_color_brewer(palette = "Greens") +
  theme_light()
```

:::

##


```{r}
#| echo: false
#| results: asis
create_buttons(NULL)
```
